### ISSUE TITLE
Rethink QS keywords

### ISSUE THREAD

**Issue by dolphinspired** [dolphinspired/PlayerMadeQuests#39]
How should this be used? Currently it is...
```
quest name="whatever" description="longer whatever"
```
But this would get very long with lots of fields. Something like this might be better:
```
quest name "I just want to dance"
quest description "he really does just want to dance"
```
But then again, writing `quest` and `objective` does seem a little bit redundant. It would honestly work better in sort of a yaml structure, which could work if the editor was a little... nicer to use.
```yaml
quest:
  name: I just want to dance
  description: he really does just want to dance
  faction: Horde required
  level:
    min: 30
    max: 40
objectives:
  - kill 5 "Mangy Wolf"
  - talkto Rexxar
  - explore "Elwynn Forest" x=2 y=4
```
Look into this! https://github.com/peposso/lua-tinyyaml

Then again, why not write it in straight Lua if we're getting to that point?
```lua
{
  quest = {
    name = "I just want to dance",
    description = "he really does just want to dance",
    faction = "Horde",
    level = {
      min = 30,
      max = 40
    }
  },
  objectives = {
    {
      "I'm already tired of writing this"
    }
  }
}
```
Too much punctuation, that's why!
